SELECT
    DP.PRODUCT_NAME,
    DP.CATEGORY,
    SUM(FO.REVENUE) AS TOTAL_REVENUE,
    SUM(FO.QUANTITY) AS TOTAL_QUANTITY
FROM GOLD.FACT_ORDERS FO
LEFT JOIN SILVER.DIM_PRODUCT DP
    ON FO.PRODUCT_ID = DP.PRODUCT_ID
GROUP BY
    DP.PRODUCT_NAME,
    DP.CATEGORY
