SELECT
    SR.TERRITORY,
    SUM(FO.REVENUE) AS TOTAL_REVENUE,
    SUM(FO.QUANTITY) AS TOTAL_QUANTITY,
    COUNT(FI.INTERACTION_ID) AS TOTAL_INTERACTIONS
FROM GOLD.FACT_ORDERS FO
LEFT JOIN SILVER.DIM_SALES_REP SR
    ON FO.REP_ID = SR.REP_ID
LEFT JOIN GOLD.FACT_INTERACTIONS FI
    ON FO.REP_ID = FI.REP_ID
GROUP BY SR.TERRITORY
