# Table DDL Definitions

ACCOUNTS_DDL = """
CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ACCOUNT_ID VARCHAR,
    ACCOUNT_NAME VARCHAR,
    ACCOUNT_TYPE VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    REGION VARCHAR
)
"""

PRODUCTS_DDL = """
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    BRAND VARCHAR,
    CATEGORY VARCHAR
)
"""

ORDERS_DDL = """
CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    REP_ID VARCHAR,
    ORDER_DATE DATE,
    QUANTITY NUMBER,
    REVENUE NUMBER
)
"""

INVENTORY_DDL = """
CREATE TABLE IF NOT EXISTS INVENTORY (
    PRODUCT_ID VARCHAR,
    INVENTORY_DATE DATE,
    STOCK_QUANTITY NUMBER
)
"""

INTERACTIONS_DDL = """
CREATE TABLE IF NOT EXISTS INTERACTIONS (
    INTERACTION_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    REP_ID VARCHAR,
    INTERACTION_DATE DATE,
    INTERACTION_TYPE VARCHAR
)
"""

SALES_REP_DDL = """
CREATE TABLE IF NOT EXISTS SALES_REP (
    REP_ID VARCHAR,
    REP_NAME VARCHAR,
    TERRITORY VARCHAR
)
"""