SELECT
    DA.ACCOUNT_NAME,
    DA.ACCOUNT_TYPE,
    DA.REGION,
    SUM(FO.REVENUE) AS TOTAL_REVENUE,
    SUM(FO.QUANTITY) AS TOTAL_QUANTITY,
    COUNT(FI.INTERACTION_ID) AS TOTAL_INTERACTIONS
FROM SILVER.DIM_ACCOUNT DA
LEFT JOIN GOLD.FACT_ORDERS FO
    ON DA.ACCOUNT_ID = FO.ACCOUNT_ID
LEFT JOIN GOLD.FACT_INTERACTIONS FI
    ON DA.ACCOUNT_ID = FI.ACCOUNT_ID
GROUP BY
    DA.ACCOUNT_NAME,
    DA.ACCOUNT_TYPE,
    DA.REGION
